---
- name: Install vim-nox
  sudo: yes
  apt: name="vim-nox" state=present

- name: Install vim-plug
  shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Generate .vimrc
  template: src="vimrc" dest="/home/{{user}}/.vimrc"
  tags:
    - config
